apiVersion: v2
name: unikorn-baremetal
description: A Helm chart for deploying Unikorn baremetal Service

type: application

version: v0.1.0
appVersion: v0.1.0

icon: https://raw.githubusercontent.com/unikorn-cloud/assets/main/images/logos/dark-on-light/icon.png

dependencies:
- name: unikorn-common
  version: v0.1.9
  repository: https://unikorn-cloud.github.io/helm-common
