apiVersion: v2
name: unikorn-compute
description: A Helm chart for deploying Unikorn compute Service

type: application

version: v0.1.4
appVersion: v0.1.4

icon: https://raw.githubusercontent.com/unikorn-cloud/assets/main/images/logos/dark-on-light/icon.png

dependencies:
- name: unikorn-common
  version: v0.1.13
  repository: https://unikorn-cloud.github.io/helm-common
