apiVersion: v2
name: unikorn-compute
description: A Helm chart for deploying Unikorn compute Service

type: application

version: v1.3.0-rc1
appVersion: v1.3.0-rc1

icon: https://raw.githubusercontent.com/unikorn-cloud/assets/main/images/logos/dark-on-light/icon.png

dependencies:
- name: unikorn-common
  version: v0.1.15
  repository: https://nscaledev.github.io/uni-helm-common
